### ISSUE TITLE
Any plans to continue the development of this lib?

### ISSUE THREAD

**Issue by renannprado** [gsquire/reroute#19]
I've just came across this library in my quest of trying to implement a REST API in Rust. The lib looks very nice, but has not received an update for while. Are there plans to continue the development of this one is it it abandoned?

**Comment by gsquire** [comment]
Hi @renannprado. I wouldn't consider this library abandoned. I just haven't dedicated a lot of time to it and only wanted to update it with the new asynchronous features. This will probably happen soon.

**Comment by renannprado** [comment]
@gsquire is it asking too much what "how soon" means?

I'm asking 'cause I see the a PR open for a long time...
Do you think you can guide someone to do the necessary changes if necessary?

**Comment by gsquire** [comment]
I let that PR go stale because the hyper API is a moving target still. I'd be happy to try and shepherd a new patch but I am hesitant to start one until hyper has a new release that is more polished.

If you are feeling ambitious, I can do code reviews as needed.

**Comment by renannprado** [comment]
Still a moving target? that's sad to hear :(

Then it's not worth my time either...
I think I can live with current version of this lib + hyper 0.10

Let's hope they have a stable release soon.

Thanks!

**Comment by gsquire** [comment]
Hi @renannprado,

I found some free time and just published version 0.4.0 if you want to give the `async` API a spin. It's a little different so check out the example if you get stuck or make a new issue.

Thanks!
