### ISSUE TITLE
Cannot use closures to pass data/variables into a handler

### ISSUE THREAD

**Issue by amandasaurus** [gsquire/reroute#6]
If you're using `hyper` directly, the [`handle` function can accept functions or closures](http://hyper.rs/hyper/v0.9.6/hyper/server/index.html), however in `reroute`, you can only pass in functions to `.get`/`.post`/etc. When using hyper, I used closures to pass variables that were calculated within my main programme which some requested needed. `reroute` accepting only functions means that I can't do this. I get this error when trying to use a closure:

```
src/cache.rs:79:31: 79:134 error: mismatched types:
 expected `fn(hyper::server::request::Request<'_, '_>, hyper::server::response::Response<'_>, std::option::Option<std::vec::Vec<std::string::String>>)`,
    found `[closure@src/cache.rs:79:31: 79:134 tilejson_contents:_]`
(expected fn pointer,
    found closure) [E0308]
```

I'm new to rust, so I might be missing something, but am I right in saying that you cannot have this approach (passing variables into the handlers) with reroute?

**Comment by amandasaurus** [comment]
The [Rust book section on closures](https://doc.rust-lang.org/book/closures.html) implies that a closure should have a type of `Fn(...)`, and in reroute, the type is `fn(...)`. I changed the `fn` to a `Fn`, and suddenly I'm getting oodles of compilation errors to do with `RouterFn`. I didn't know `fn` and `Fn` were different in Rust!

**Comment by gsquire** [comment]
Hi @rory, thanks for writing this up.

In hyper, the `handle` function for the `Server` struct accepts an argument that implements the `Handler` trait. Thus you can pass in a closure of the same form as long as they satisfy that trait. For this crate however the functions that define routes accept a [custom function type](https://gsquire.github.io/docs/rust/reroute/type.RouterFn.html). I could look into designing a trait that could loosen up this restriction as you illustrated.

> I didn't know fn and Fn were different in Rust!

The differences here are `fn` is a keyword to define a function whereas `Fn` is a trait that defines how a function argument should behave. See the documentation [here](https://doc.rust-lang.org/std/ops/trait.Fn.html).

I hope this helps!

**Comment by dashed** [comment]
I'm facing the same issues. I also hadn't realized that `RouterFn` was using `fn` and not `Fn`.

I brought this up on #rust irc, but there didn't seem to be a direction on how to get around it: https://botbot.me/mozilla/rust/2016-05-27/?msg=66799780&page=2

**Comment by gsquire** [comment]
Hi @dashed. The reason it is not `Fn` is because it does implement the `Sized` trait. So I might have to change the entire API this provides to support that. I will look into it further.

**Comment by dashed** [comment]
Yeah, I tried `Fn` definition, and dynamically sized types isn't trivial to get around.

**Comment by gsquire** [comment]
Due to the fact that I am using a hash map to store the routes, I want to say that using closures here won't work. I will keep this open if anybody wants to submit a PR.

**Comment by gsquire** [comment]
@dashed @rory Sorry it took a while to get back to this issue, but with the PR mentioned in this issue you can now use closures as arguments. Let me know how it looks and I can create a new release on https://crates.io.

**Comment by gsquire** [comment]
A simple example you can use to test:

``` rust
router.get("/", |_: Request, res: Response, _: Captures| {
    res.send(b"Hello").unwrap();
});
```

**Comment by dashed** [comment]
@gsquire Thanks! I'll check it out. I ended up privately forking reroute to better fit my use cases e.g. custom function signature.

**Comment by gsquire** [comment]
@dashed Sweet, hope it works out for you.

**Comment by saggit** [comment]
Nice work, like this example:

``` rust
router.get("/", |_: Request, res: Response, _: Captures| {
    res.send(b"Hello").unwrap();
});
```

the only var we can use here is Captures, which is a `Option<Vec<String>>`, Is there any way to pass a db connection pool like [r2d2-postgres](https://github.com/sfackler/r2d2-postgres)?

**Comment by gsquire** [comment]
Hi @saggit there isn't a way to do that. The API can't support arbitrary types as a parameter to routing functions. I'm not sure there is a way to do this, but I can investigate.

If you have any further questions, feel free to open another issue.
